# Generated by Django 6.0.1 on 2026-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
